name: Trigger QA repo after merge

on:
  push:
    branches:
      - main
      - master

jobs:
  trigger-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger QA workflow
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.QA_REPO_TOKEN }}" \
            https://api.github.com/repos/AlexLisovy/MegaportAssesment/actions/workflows/run-tests.yml/dispatches \
            -d '{
              "ref": "main",
              "inputs": {
                "source_sha": "${{ github.sha }}",
                "source_branch": "${{ github.ref_name }}"
              }
            }'
