name: Trigger QA tests after push to master

on:
  push:
    branches:
      - master

jobs:
  trigger-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger QA workflow in MegaportAssesment
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.QA_REPO_TOKEN }}" \
            https://api.github.com/repos/AlexLisovy/MegaportAssesment/actions/workflows/run-tests.yml/dispatches \
            -d '{
              "ref": "master",
              "inputs": {
                "source_repo": "${{ github.repository }}",
                "source_branch": "${{ github.ref_name }}",
                "source_sha": "${{ github.sha }}"
              }
            }'
